export const EVENTS = {
  // ── Solicitações ─────────────────────────────────────────────────
  PURCHASE_REQUEST_CREATED:    "PURCHASE_REQUEST_CREATED",
  PURCHASE_REQUEST_SUBMITTED:  "PURCHASE_REQUEST_SUBMITTED",   // ABERTA → AGUARDANDO_APROVACAO
  PURCHASE_REQUEST_APPROVED:   "PURCHASE_REQUEST_APPROVED",
  PURCHASE_REQUEST_REJECTED:   "PURCHASE_REQUEST_REJECTED",
  PURCHASE_REQUEST_CANCELLED:  "PURCHASE_REQUEST_CANCELLED",
  PURCHASE_REQUEST_DELETED:    "PURCHASE_REQUEST_DELETED",

  // ── Pedidos ──────────────────────────────────────────────────────
  PURCHASE_ORDER_CREATED:            "PURCHASE_ORDER_CREATED",
  PURCHASE_ORDER_AWAITING_APPROVAL:  "PURCHASE_ORDER_AWAITING_APPROVAL", // → AGUARDANDO_APROVACAO
  PURCHASE_ORDER_APPROVED:           "PURCHASE_ORDER_APPROVED",
  PURCHASE_ORDER_EMITTED:            "PURCHASE_ORDER_EMITTED",           // → EMITIDO
  PURCHASE_ORDER_SENT:               "PURCHASE_ORDER_SENT",              // → AGUARDANDO_RECEBIMENTO
  PURCHASE_ORDER_REJECTED:           "PURCHASE_ORDER_REJECTED",           // → REJEITADO
  PURCHASE_ORDER_RETURNED_TO_DRAFT:  "PURCHASE_ORDER_RETURNED_TO_DRAFT",  // REJEITADO → RASCUNHO
  PURCHASE_ORDER_CANCELLED:          "PURCHASE_ORDER_CANCELLED",
  PURCHASE_ORDER_RECEIVED_PARTIAL:   "PURCHASE_ORDER_RECEIVED_PARTIAL",
  PURCHASE_ORDER_RECEIVED_FULL:      "PURCHASE_ORDER_RECEIVED_FULL",
  PURCHASE_ORDER_EDITED:             "PURCHASE_ORDER_EDITED",
  PURCHASE_ORDER_DELETED:            "PURCHASE_ORDER_DELETED",

  // ── Recebimentos ─────────────────────────────────────────────────
  PURCHASE_RECEIPT_REGISTERED: "PURCHASE_RECEIPT_REGISTERED",

  // ── Fornecedores ─────────────────────────────────────────────────
  // -- Retorno de Pedido
  PURCHASE_ORDER_RETURN_REQUESTED: "PURCHASE_ORDER_RETURN_REQUESTED",
  PURCHASE_ORDER_RETURN_APPROVED:  "PURCHASE_ORDER_RETURN_APPROVED",
  PURCHASE_ORDER_RETURN_REJECTED:  "PURCHASE_ORDER_RETURN_REJECTED",

  // -- Devolucao de Pedido
  PURCHASE_ORDER_DEVOLUTION_CREATED:   "PURCHASE_ORDER_DEVOLUTION_CREATED",
  PURCHASE_ORDER_DEVOLUTION_APPROVED:  "PURCHASE_ORDER_DEVOLUTION_APPROVED",
  PURCHASE_ORDER_DEVOLUTION_REJECTED:  "PURCHASE_ORDER_DEVOLUTION_REJECTED",
  PURCHASE_ORDER_DEVOLUTION_SENT:      "PURCHASE_ORDER_DEVOLUTION_SENT",
  PURCHASE_ORDER_DEVOLUTION_DELIVERED: "PURCHASE_ORDER_DEVOLUTION_DELIVERED",

  SUPPLIER_CREATED: "SUPPLIER_CREATED",
  SUPPLIER_UPDATED: "SUPPLIER_UPDATED",
  SUPPLIER_DELETED: "SUPPLIER_DELETED",

  // ── Gate de conformidade — pendências críticas ──────────────────────
  PURCHASE_PENDENCY_ESCALATED:           "PURCHASE_PENDENCY_ESCALATED",
  PURCHASE_PENDENCY_EXCEPTION_REQUESTED: "PURCHASE_PENDENCY_EXCEPTION_REQUESTED",
  PURCHASE_PENDENCY_EXCEPTION_DECIDED:   "PURCHASE_PENDENCY_EXCEPTION_DECIDED",

  // ── Beneficiamento (entidade própria — pedidos_beneficiamento, NÃO é
  // PURCHASE_ORDER_*, não deve notificar quem aprova pedido normal) ──────
  BENEFICIAMENTO_CREATED:           "BENEFICIAMENTO_CREATED",
  BENEFICIAMENTO_AWAITING_APPROVAL: "BENEFICIAMENTO_AWAITING_APPROVAL",
  BENEFICIAMENTO_APPROVED:          "BENEFICIAMENTO_APPROVED",
  BENEFICIAMENTO_REJECTED:          "BENEFICIAMENTO_REJECTED",
  BENEFICIAMENTO_EMITTED:           "BENEFICIAMENTO_EMITTED",
  BENEFICIAMENTO_SENT:              "BENEFICIAMENTO_SENT",
  BENEFICIAMENTO_CANCELLED:         "BENEFICIAMENTO_CANCELLED",
  BENEFICIAMENTO_RECEIVED_PARTIAL:  "BENEFICIAMENTO_RECEIVED_PARTIAL",
  BENEFICIAMENTO_RECEIVED_FULL:     "BENEFICIAMENTO_RECEIVED_FULL",
} as const;

export type EventTipo = typeof EVENTS[keyof typeof EVENTS];

export type DomainEvent = {
  id?: string;
  tipo: string;
  payload: Record<string, unknown>;
  company_id: string;
};
