import "server-only";
import { createAdminClient } from "@/shared/database/supabase-admin";
import type { CreateElementInput, CreateEnvironmentInput, CreateMeasurementInput, CreateObservationInput, CreateVisitInput } from "../schemas";
import type { VisitDetail, VisitFilters, VisitListItem } from "../types";

const listSelect = `id, obra_id, medidor_responsavel_id, status, prioridade, agendada_para, progresso, observacoes_gerais, obra:obras(id,nome,codigo,cidade,endereco,cliente:clientes(id,nome,razao_social)), medidor:usuarios!measure_visitas_medidor_responsavel_id_fkey(id,nome)`;
const detailSelect = `${listSelect}, iniciada_em, finalizada_em, justificativa_finalizacao, criado_em, atualizado_em, membros:measure_visita_membros(usuario_id,papel_na_visita,usuario:usuarios!measure_visita_membros_usuario_id_fkey(nome)), ambientes:measure_ambientes(id,visita_id,nome,codigo,pavimento,descricao,sequencia,status,observacoes,arquivado_em,elementos:measure_elementos(id,ambiente_id,nome,codigo,tipo,quantidade,descricao,sequencia,status,requer_atencao,arquivado_em,medidas:measure_medidas(id,elemento_id,grupo,tipo,nome,valor,unidade,tolerancia,posicao,observacao,origem,estado,medida_em))), observacoes:measure_observacoes(id,visita_id,ambiente_id,elemento_id,medida_id,categoria,texto,importante,resolvida_em,criado_em,responsavel:usuarios!measure_observacoes_responsavel_id_fkey(nome)), historico:measure_historico(id,acao,entidade_tipo,entidade_id,dados_antes,dados_depois,criado_em,usuario:usuarios!measure_historico_usuario_id_fkey(nome))`;
function fail(error: { message: string } | null) { if (error) throw new Error(error.message); }
function required<T>(data: T | null, message = "Registro não retornado pelo banco."): T { if (data === null) throw new Error(message); return data; }

export async function listVisits(filters: VisitFilters = {}) {
  const admin = createAdminClient(); const page = Math.max(1, filters.pagina ?? 1); const size = Math.min(50, Math.max(5, filters.porPagina ?? 12));
  let q = admin.from("measure_visitas").select(listSelect, { count: "exact" }).is("excluido_em", null);
  if (filters.status) q = q.eq("status", filters.status); if (filters.medidorId) q = q.eq("medidor_responsavel_id", filters.medidorId); if (filters.obraId) q = q.eq("obra_id", filters.obraId); if (filters.prioridade) q = q.eq("prioridade", filters.prioridade); if (filters.de) q = q.gte("agendada_para", filters.de); if (filters.ate) q = q.lte("agendada_para", filters.ate);
  const { data, error, count } = await q.order("agendada_para", { ascending: filters.ordem === "asc", nullsFirst: false }).range((page - 1) * size, page * size - 1); fail(error);
  let rows = (data ?? []) as unknown as VisitListItem[]; if (filters.busca) { const term = filters.busca.toLocaleLowerCase("pt-BR"); rows = rows.filter((v) => `${v.obra?.nome ?? ""} ${v.obra?.codigo ?? ""} ${v.obra?.cliente?.nome ?? ""}`.toLocaleLowerCase("pt-BR").includes(term)); }
  return { data: rows, total: count ?? rows.length, pagina: page, porPagina: size };
}
export async function getVisit(id: string): Promise<VisitDetail | null> { const { data, error } = await createAdminClient().from("measure_visitas").select(detailSelect).eq("id", id).is("excluido_em", null).maybeSingle(); fail(error); return data as unknown as VisitDetail | null; }
export async function createVisit(input: CreateVisitInput, userId: string) { const admin=createAdminClient(); const { data: obra, error: oe }=await admin.from("obras").select("id,nome,codigo,endereco,cidade,estado,cep,cliente:clientes(id,nome,razao_social)").eq("id",input.obra_id).single(); fail(oe); const {data,error}=await admin.from("measure_visitas").insert({...input,criado_por:userId,contexto_obra_snapshot:required(obra,"Obra não encontrada.")}).select("id").single(); fail(error); const row=required(data); await admin.from("measure_visita_membros").insert({visita_id:row.id,usuario_id:input.medidor_responsavel_id,papel_na_visita:"responsavel",criado_por:userId}); await addHistory(row.id,userId,"visita_criada","visita",row.id,null,input); return row.id as string; }
export async function updateVisit(id:string,input:Record<string,unknown>,userId:string,expectedVersion?:number){const admin=createAdminClient();const {data:before}=await admin.from("measure_visitas").select("*").eq("id",id).single();let query=admin.from("measure_visitas").update({...input,atualizado_por:userId,atualizado_em:new Date().toISOString()}).eq("id",id);if(expectedVersion!==undefined)query=query.eq("versao",expectedVersion);const {data,error}=await query.select("id").maybeSingle();fail(error);if(expectedVersion!==undefined&&!data)throw new Error("VERSION_CONFLICT");await addHistory(id,userId,"visita_editada","visita",id,before,input);}
export async function createEnvironment(input:CreateEnvironmentInput,userId:string){const {data,error}=await createAdminClient().from("measure_ambientes").insert({...input,criado_por:userId}).select("id").single();fail(error);const row=required(data);await addHistory(input.visita_id,userId,"ambiente_criado","ambiente",row.id,null,input);return row.id as string;}
export async function createElement(input:CreateElementInput,userId:string){const admin=createAdminClient();const {data,error}=await admin.from("measure_elementos").insert({...input,criado_por:userId,responsavel_registro_id:userId}).select("id,ambiente:measure_ambientes(visita_id)").single();fail(error);const row=required(data);const ambiente=row.ambiente as unknown as {visita_id:string};await addHistory(ambiente.visita_id,userId,"elemento_criado","elemento",row.id,null,input);return row.id as string;}
export async function createMeasurement(input:CreateMeasurementInput,userId:string){const admin=createAdminClient();const {data,error}=await admin.from("measure_medidas").insert({...input,medida_em:input.medida_em??new Date().toISOString(),responsavel_id:userId,criado_por:userId}).select("id,elemento:measure_elementos(ambiente:measure_ambientes(visita_id))").single();fail(error);const row=required(data);const el=row.elemento as unknown as {ambiente:{visita_id:string}};await addHistory(el.ambiente.visita_id,userId,"medida_criada","medida",row.id,null,input);return row.id as string;}
export async function createObservation(input:CreateObservationInput,userId:string){const {data,error}=await createAdminClient().from("measure_observacoes").insert({...input,responsavel_id:userId,criado_por:userId}).select("id").single();fail(error);const row=required(data);await addHistory(input.visita_id,userId,"observacao_criada","observacao",row.id,null,input);return row.id as string;}
export async function resolveObservation(id:string,resolved:boolean,userId:string){const admin=createAdminClient();const {data,error}=await admin.from("measure_observacoes").update({resolvida_em:resolved?new Date().toISOString():null,atualizado_por:userId,atualizado_em:new Date().toISOString()}).eq("id",id).select("visita_id").single();fail(error);const row=required(data);await addHistory(row.visita_id,userId,resolved?"observacao_resolvida":"observacao_reaberta","observacao",id,null,{resolved});}
export async function updateObservation(id:string,input:Record<string,unknown>,userId:string){const {error}=await createAdminClient().from("measure_observacoes").update({...input,atualizado_por:userId,atualizado_em:new Date().toISOString()}).eq("id",id);fail(error);}
export async function listSupport(){const admin=createAdminClient();const [obras,users]=await Promise.all([admin.from("obras").select("id,nome,codigo,cliente:clientes(nome)").is("deleted_at",null).order("nome"),admin.from("usuarios").select("id,nome").eq("ativo",true).order("nome")]);fail(obras.error);fail(users.error);return {obras:obras.data??[],usuarios:users.data??[]};}
export async function setProgress(id:string,progress:number,userId:string){const {error}=await createAdminClient().from("measure_visitas").update({progresso:progress,atualizado_por:userId,atualizado_em:new Date().toISOString()}).eq("id",id);fail(error);}
export async function updateEntity(table:"measure_ambientes"|"measure_elementos"|"measure_medidas",id:string,input:Record<string,unknown>,userId:string){const {error}=await createAdminClient().from(table).update({...input,atualizado_por:userId,atualizado_em:new Date().toISOString()}).eq("id",id);fail(error);}
export async function reorderEntities(table:"measure_ambientes"|"measure_elementos",ids:string[],userId:string){const admin=createAdminClient();for(const [sequencia,id] of ids.entries()){const {error}=await admin.from(table).update({sequencia,atualizado_por:userId,atualizado_em:new Date().toISOString()}).eq("id",id);fail(error);}}
export async function archiveEntity(table:"measure_ambientes"|"measure_elementos",id:string,archived:boolean,userId:string){const admin=createAdminClient();const {data,error}=await admin.from(table).select("versao").eq("id",id).single();fail(error);await updateEntity(table,id,{arquivado_em:archived?new Date().toISOString():null,versao:(data?.versao??0)+1},userId);}
export async function getElement(id:string){const {data,error}=await createAdminClient().from("measure_elementos").select("*,ambiente:measure_ambientes(visita_id),medidas:measure_medidas(tipo,nome,grupo,unidade,posicao,observacao)").eq("id",id).single();fail(error);return required(data);}
export async function siblingElementNames(environmentId:string){const {data,error}=await createAdminClient().from("measure_elementos").select("nome").eq("ambiente_id",environmentId).is("excluido_em",null);fail(error);return (data??[]).map(x=>x.nome as string);}
export async function addHistory(visitaId:string,userId:string,acao:string,entityType:string,entityId:string|null,before:unknown,after:unknown){const {error}=await createAdminClient().from("measure_historico").insert({visita_id:visitaId,usuario_id:userId,acao,entidade_tipo:entityType,entidade_id:entityId,dados_antes:before,dados_depois:after});fail(error);}
