import React from 'react';
import {ActivityIndicator,Pressable,StyleProp,StyleSheet,Text,TextInput,TextInputProps,View,ViewStyle} from 'react-native';
import type {LucideIcon} from 'lucide-react-native';
import {colors,radius} from './theme';

export function AppButton({label,onPress,icon:Icon,variant='primary',disabled=false,small=false,full=false}:{label:string;onPress:()=>void;icon?:LucideIcon;variant?:'primary'|'secondary'|'ghost'|'danger'|'success'|'warning';disabled?:boolean;small?:boolean;full?:boolean}){
  const palette={primary:[colors.primary,colors.white],secondary:[colors.surface3,colors.text],ghost:['transparent',colors.text2],danger:[colors.danger,colors.white],success:[colors.success,colors.white],warning:[colors.warning,colors.white]}[variant];
  return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,{backgroundColor:palette[0]},small&&s.buttonSmall,full&&s.full,pressed&&s.pressed,disabled&&s.disabled]}>{Icon&&<Icon size={small?15:18} color={palette[1]} strokeWidth={2}/>}<Text style={[s.buttonText,{color:palette[1]},small&&s.buttonTextSmall]}>{label}</Text></Pressable>;
}
export function FieldInput(props:TextInputProps){return <TextInput placeholderTextColor={colors.text3} {...props} style={[s.input,props.multiline&&s.multiline,props.style]}/>;}
export function Card({children,style}:{children:React.ReactNode;style?:StyleProp<ViewStyle>}){return <View style={[s.card,style]}>{children}</View>;}
export function Badge({label,tone='default'}:{label:string;tone?:'default'|'primary'|'success'|'warning'|'danger'|'info'}){const p={default:[colors.surface3,colors.text2],primary:[colors.primarySoft,colors.primary],success:[colors.successSoft,colors.success],warning:[colors.warningSoft,colors.warning],danger:[colors.dangerSoft,colors.danger],info:[colors.infoSoft,colors.info]}[tone];return <View style={[s.badge,{backgroundColor:p[0]}]}><View style={[s.dot,{backgroundColor:p[1]}]}/><Text style={[s.badgeText,{color:p[1]}]}>{label}</Text></View>;}
export function ProgressBar({value}:{value:number}){return <View style={s.progress}><View style={[s.progressFill,{width:`${Math.max(0,Math.min(100,value))}%`}]}/></View>;}
export function Loading(){return <View style={s.loading}><ActivityIndicator size="large" color={colors.primary}/><Text style={s.loadingText}>Carregando SquadMeasure…</Text></View>;}
const s=StyleSheet.create({button:{height:42,paddingHorizontal:16,borderRadius:radius.md,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center'},buttonSmall:{height:34,paddingHorizontal:11},buttonText:{fontSize:14,fontWeight:'700'},buttonTextSmall:{fontSize:12},full:{width:'100%'},pressed:{opacity:.82,transform:[{scale:.98}]},disabled:{opacity:.4},input:{minHeight:46,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.surface,paddingHorizontal:14,paddingVertical:10,fontSize:15,color:colors.text},multiline:{minHeight:92,textAlignVertical:'top'},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:16,shadowColor:'#000',shadowOpacity:.04,shadowRadius:8,shadowOffset:{width:0,height:2},elevation:1},badge:{alignSelf:'flex-start',height:25,borderRadius:radius.full,paddingHorizontal:9,flexDirection:'row',alignItems:'center',gap:6},dot:{width:6,height:6,borderRadius:3},badgeText:{fontSize:11,fontWeight:'700',textTransform:'capitalize'},progress:{height:7,borderRadius:radius.full,backgroundColor:colors.surface3,overflow:'hidden'},progressFill:{height:'100%',borderRadius:radius.full,backgroundColor:colors.accent},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:14,backgroundColor:colors.bg},loadingText:{color:colors.text2,fontSize:14}});
