export const EVENTS = {
  // ── Solicitações ─────────────────────────────────────────────────
  PURCHASE_REQUEST_CREATED:    "PURCHASE_REQUEST_CREATED",
  PURCHASE_REQUEST_SUBMITTED:  "PURCHASE_REQUEST_SUBMITTED",   // ABERTA → AGUARDANDO_APROVACAO
  PURCHASE_REQUEST_APPROVED:   "PURCHASE_REQUEST_APPROVED",
  PURCHASE_REQUEST_REJECTED:   "PURCHASE_REQUEST_REJECTED",
  PURCHASE_REQUEST_CANCELLED:  "PURCHASE_REQUEST_CANCELLED",
  PURCHASE_REQUEST_DELETED:    "PURCHASE_REQUEST_DELETED",

  // ── Pedidos ──────────────────────────────────────────────────────
  PURCHASE_ORDER_CREATED:            "PURCHASE_ORDER_CREATED",
  PURCHASE_ORDER_AWAITING_APPROVAL:  "PURCHASE_ORDER_AWAITING_APPROVAL", // → AGUARDANDO_APROVACAO
  PURCHASE_ORDER_APPROVED:           "PURCHASE_ORDER_APPROVED",
  PURCHASE_ORDER_SENT:               "PURCHASE_ORDER_SENT",              // → EMITIDO / AGUARDANDO_RECEBIMENTO
  PURCHASE_ORDER_CANCELLED:          "PURCHASE_ORDER_CANCELLED",
  PURCHASE_ORDER_RECEIVED_PARTIAL:   "PURCHASE_ORDER_RECEIVED_PARTIAL",
  PURCHASE_ORDER_RECEIVED_FULL:      "PURCHASE_ORDER_RECEIVED_FULL",
  PURCHASE_ORDER_EDITED:             "PURCHASE_ORDER_EDITED",
  PURCHASE_ORDER_DELETED:            "PURCHASE_ORDER_DELETED",

  // ── Recebimentos ─────────────────────────────────────────────────
  PURCHASE_RECEIPT_REGISTERED: "PURCHASE_RECEIPT_REGISTERED",

  // ── Fornecedores ─────────────────────────────────────────────────
  SUPPLIER_CREATED: "SUPPLIER_CREATED",
  SUPPLIER_UPDATED: "SUPPLIER_UPDATED",
  SUPPLIER_DELETED: "SUPPLIER_DELETED",
} as const;

export type EventTipo = typeof EVENTS[keyof typeof EVENTS];

export type DomainEvent = {
  id?: string;
  tipo: string;
  payload: Record<string, unknown>;
  company_id: string;
};
