import "server-only";
import * as repo from "../repositories";
import type { CreateElementInput, CreateEnvironmentInput, CreateMeasurementInput, CreateObservationInput, CreateVisitInput } from "../schemas";
import type { VisitStatus } from "../types";
import { assertTransition, calculateProgress, nextDuplicateName } from "./rules";
export const listVisits=repo.listVisits; export const getVisit=repo.getVisit; export const listSupport=repo.listSupport;
export async function createVisit(input:CreateVisitInput,userId:string){return repo.createVisit(input,userId);}
export async function editVisit(id:string,input:Record<string,unknown>,userId:string){const visit=await repo.getVisit(id);if(!visit)throw new Error("Visita não encontrada.");if(["concluida","cancelada"].includes(visit.status))throw new Error("Visita encerrada não pode ser editada.");await repo.updateVisit(id,input,userId);}
export async function addEnvironment(input:CreateEnvironmentInput,userId:string){await ensureMutable(input.visita_id);const id=await repo.createEnvironment(input,userId);await refreshProgress(input.visita_id,userId);return id;}
export async function addElement(input:CreateElementInput,userId:string){const visit=await visitFromEnvironment(input.ambiente_id);await ensureMutable(visit.id);const id=await repo.createElement(input,userId);await refreshProgress(visit.id,userId);return id;}
export async function addMeasurement(input:CreateMeasurementInput,userId:string){const visit=await visitFromElement(input.elemento_id);await ensureMutable(visit.id);const id=await repo.createMeasurement(input,userId);await refreshProgress(visit.id,userId);return id;}
export async function addObservation(input:CreateObservationInput,userId:string){await ensureMutable(input.visita_id);return repo.createObservation(input,userId);}
export async function editMeasurement(id:string,elementId:string,input:Record<string,unknown>,userId:string){const visit=await visitFromElement(elementId);await ensureMutable(visit.id);await repo.updateEntity("measure_medidas",id,input,userId);await repo.addHistory(visit.id,userId,"medida_editada","medida",id,null,input);await refreshProgress(visit.id,userId);}
export async function editObservation(id:string,visitId:string,input:Record<string,unknown>,userId:string){await ensureMutable(visitId);const { resolvida, ...patch }=input;if(Object.keys(patch).length)await repo.updateObservation(id,patch,userId);if(typeof resolvida==="boolean")await repo.resolveObservation(id,resolvida,userId);}
export async function resolveObservation(id:string,resolved:boolean,userId:string){return repo.resolveObservation(id,resolved,userId);}
export async function editEnvironment(id:string,visitId:string,input:Record<string,unknown>,userId:string){await ensureMutable(visitId);await repo.updateEntity("measure_ambientes",id,input,userId);await repo.addHistory(visitId,userId,"ambiente_editado","ambiente",id,null,input);await refreshProgress(visitId,userId);}
export async function reorderEnvironments(visitId:string,ids:string[],userId:string){await ensureMutable(visitId);await repo.reorderEntities("measure_ambientes",ids,userId);await repo.addHistory(visitId,userId,"ambientes_reordenados","ambiente",null,null,{ids});}
export async function archiveEnvironment(id:string,visitId:string,archived:boolean,userId:string){await ensureMutable(visitId);await repo.archiveEntity("measure_ambientes",id,archived,userId);await repo.addHistory(visitId,userId,archived?"ambiente_arquivado":"ambiente_restaurado","ambiente",id,null,null);await refreshProgress(visitId,userId);}
export async function editElement(id:string,environmentId:string,input:Record<string,unknown>,userId:string){const visit=await visitFromEnvironment(environmentId);await ensureMutable(visit.id);await repo.updateEntity("measure_elementos",id,input,userId);await repo.addHistory(visit.id,userId,"elemento_editado","elemento",id,null,input);await refreshProgress(visit.id,userId);}
export async function reorderElements(environmentId:string,ids:string[],userId:string){const visit=await visitFromEnvironment(environmentId);await ensureMutable(visit.id);await repo.reorderEntities("measure_elementos",ids,userId);await repo.addHistory(visit.id,userId,"elementos_reordenados","elemento",null,null,{ids});}
export async function archiveElement(id:string,environmentId:string,archived:boolean,userId:string){const visit=await visitFromEnvironment(environmentId);await ensureMutable(visit.id);await repo.archiveEntity("measure_elementos",id,archived,userId);await repo.addHistory(visit.id,userId,archived?"elemento_arquivado":"elemento_restaurado","elemento",id,null,null);await refreshProgress(visit.id,userId);}
export async function duplicateElement(id:string,userId:string){const source=await repo.getElement(id);const ambiente=source.ambiente as unknown as {visita_id:string};await ensureMutable(ambiente.visita_id);const names=await repo.siblingElementNames(source.ambiente_id);const newId=await repo.createElement({ambiente_id:source.ambiente_id,nome:nextDuplicateName(source.nome,names),codigo:null,tipo:source.tipo,quantidade:source.quantidade,descricao:source.descricao,sequencia:source.sequencia+1,status:"pendente",requer_atencao:source.requer_atencao},userId);await repo.addHistory(ambiente.visita_id,userId,"elemento_duplicado","elemento",newId,{origem_id:id},{medidas_copiadas:false});return newId;}
export async function changeStatus(id:string,to:VisitStatus,userId:string,comment?:string|null,justification?:string|null,expectedVersion?:number){const visit=await repo.getVisit(id);if(!visit)throw new Error("Visita não encontrada.");assertTransition(visit.status,to);const current=(visit as unknown as {versao?:number}).versao??expectedVersion??1;if(expectedVersion!==undefined&&current!==expectedVersion)throw new Error("VERSION_CONFLICT");const patch:Record<string,unknown>={status:to,versao:current+1};if(to==="em_andamento"&&!visit.iniciada_em)patch.iniciada_em=new Date().toISOString();if(to==="concluida")patch.finalizada_em=new Date().toISOString();if(justification)patch.justificativa_finalizacao=justification;await repo.updateVisit(id,patch,userId,expectedVersion);await repo.addHistory(id,userId,"status_alterado","visita",id,{status:visit.status},{status:to,comentario:comment});}
export async function review(id:string,decision:"aprovar"|"solicitar_correcao",comment:string,userId:string){await changeStatus(id,decision==="aprovar"?"concluida":"correcao_solicitada",userId,comment);await repo.createObservation({visita_id:id,categoria:"revisao_necessaria",texto:comment,importante:decision==="solicitar_correcao"},userId);}
async function ensureMutable(id:string){const v=await repo.getVisit(id);if(!v)throw new Error("Visita não encontrada.");if(["concluida","cancelada","aguardando_revisao"].includes(v.status))throw new Error("O estado atual não permite esta alteração.");return v;}
async function visitFromEnvironment(environmentId:string){const visits=await repo.listVisits({porPagina:50});for(const v of visits.data){const detail=await repo.getVisit(v.id);if(detail?.ambientes.some(a=>a.id===environmentId))return detail;}throw new Error("Ambiente não encontrado.");}
async function visitFromElement(elementId:string){const visits=await repo.listVisits({porPagina:50});for(const v of visits.data){const detail=await repo.getVisit(v.id);if(detail?.ambientes.some(a=>a.elementos.some(e=>e.id===elementId)))return detail;}throw new Error("Elemento não encontrado.");}
async function refreshProgress(id:string,userId:string){const v=await repo.getVisit(id);if(!v)return;const critical=new Set(["impedimento","risco","revisao_necessaria"]);const progress=calculateProgress(v.ambientes.filter(a=>!a.arquivado_em).map(a=>({status:a.status,elements:a.elementos.filter(e=>!e.arquivado_em).map(e=>({status:e.status,measurementCount:e.medidas.filter(m=>m.estado!=="invalidada").length,hasCriticalPending:v.observacoes.some(o=>o.elemento_id===e.id&&!o.resolvida_em&&critical.has(o.categoria))}))})));await repo.setProgress(id,progress,userId);}
export { nextDuplicateName };
