import { NextRequest } from "next/server";
import * as service from "@/modules/squadmeasure/services";
import { createElementSchema,createEnvironmentSchema,createMeasurementSchema,createObservationSchema,editElementSchema,editEnvironmentSchema,editMeasurementSchema,editObservationSchema } from "@/modules/squadmeasure/schemas";
import { authenticate,failure,ok,parse,requirePermission,requireVersion,requireVisitAccess,visitForParent } from "./auth";

export type EntityKind="environment"|"element"|"measurement"|"observation";
const permission:Record<EntityKind,string>={environment:"squadmeasure.gerenciar_ambientes",element:"squadmeasure.gerenciar_elementos",measurement:"squadmeasure.registrar_medidas",observation:"squadmeasure.gerenciar_observacoes"};
export async function createEntity(request:NextRequest,kind:EntityKind){try{const ctx=await authenticate(request);requirePermission(ctx,permission[kind]);const raw=await request.json();if(kind==="environment"){const body=parse(createEnvironmentSchema,raw);await requireVisitAccess(ctx,body.visita_id);const id=await service.addEnvironment(body,ctx.userId);return ok({id,version:1},201);}if(kind==="element"){const body=parse(createElementSchema,raw);await requireVisitAccess(ctx,await visitForParent("environment",body.ambiente_id));const id=await service.addElement(body,ctx.userId);return ok({id,version:1},201);}if(kind==="measurement"){const body=parse(createMeasurementSchema,raw);await requireVisitAccess(ctx,await visitForParent("element",body.elemento_id));const id=await service.addMeasurement(body,ctx.userId);return ok({id,version:1},201);}const body=parse(createObservationSchema,raw);await requireVisitAccess(ctx,body.visita_id);const id=await service.addObservation(body,ctx.userId);return ok({id,version:1},201);}catch(error){return failure(error);}}
export async function updateEntity(request:NextRequest,kind:EntityKind){try{const ctx=await authenticate(request);requirePermission(ctx,permission[kind]);const raw=await request.json();if(kind==="environment"){const body=parse(editEnvironmentSchema,raw);await requireVisitAccess(ctx,body.visita_id);const {id,visita_id,expectedVersion,arquivado,...patch}=body;await requireVersion("measure_ambientes",id,expectedVersion);if(arquivado!==undefined)await service.archiveEnvironment(id,visita_id,arquivado,ctx.userId);else await service.editEnvironment(id,visita_id,{...patch,versao:(expectedVersion??0)+1},ctx.userId);return ok({id,version:(expectedVersion??0)+1});}if(kind==="element"){const body=parse(editElementSchema,raw);await requireVisitAccess(ctx,await visitForParent("environment",body.ambiente_id));const {id,ambiente_id,expectedVersion,arquivado,...patch}=body;await requireVersion("measure_elementos",id,expectedVersion);if(arquivado!==undefined)await service.archiveElement(id,ambiente_id,arquivado,ctx.userId);else await service.editElement(id,ambiente_id,{...patch,versao:(expectedVersion??0)+1},ctx.userId);return ok({id,version:(expectedVersion??0)+1});}if(kind==="measurement"){const body=parse(editMeasurementSchema,raw);if(!body.elemento_id)throw new Error("elemento_id required");await requireVisitAccess(ctx,await visitForParent("element",body.elemento_id));const {id,elemento_id,expectedVersion,...patch}=body;await requireVersion("measure_medidas",id,expectedVersion);await service.editMeasurement(id,elemento_id,{...patch,versao:(expectedVersion??0)+1},ctx.userId);return ok({id,version:(expectedVersion??0)+1});}const body=parse(editObservationSchema,raw);await requireVisitAccess(ctx,body.visita_id);const {id,visita_id,expectedVersion,...patch}=body;await requireVersion("measure_observacoes",id,expectedVersion);await service.editObservation(id,visita_id,{...patch,versao:(expectedVersion??0)+1},ctx.userId);return ok({id,version:(expectedVersion??0)+1});}catch(error){return failure(error);}}
