using AcadApplication=Autodesk.AutoCAD.ApplicationServices.Application;
using System.Diagnostics;
namespace SquadEngineering.Plugin;
internal sealed class EngineeringPanel:UserControl
{
 private readonly Label _file=Value(),_path=Value(),_revision=Value("Rascunho local"),_latest=Value("Nenhuma versão criada"),_status=Value("● Plugin conectado");
 public EngineeringPanel(){BackColor=Color.FromArgb(247,248,250);Padding=new(18);AutoScroll=true;var layout=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true};layout.Controls.Add(new Label{Text="SQUAD ENGINEERING",Font=new("Segoe UI",15,FontStyle.Bold),ForeColor=Color.FromArgb(22,101,52),AutoSize=true});layout.Controls.Add(new Label{Text="Controle de projetos e revisões",AutoSize=true,Margin=new(0,0,0,20)});Field(layout,"ARQUIVO ATUAL",_file);Field(layout,"CAMINHO",_path);Field(layout,"REVISÃO LOCAL",_revision);Field(layout,"ÚLTIMA VERSÃO",_latest);Field(layout,"STATUS",_status);var save=ActionButton("Salvar desenho");save.Click+=(_,_)=>AcadApplication.DocumentManager.MdiActiveDocument?.SendStringToExecute("_.QSAVE ",true,false,false);layout.Controls.Add(save);var open=ActionButton("Abrir versões locais");open.Click+=(_,_)=>OpenVersions();layout.Controls.Add(open);Controls.Add(layout);Load+=(_,_)=>RefreshDrawingInformation();}
 public void RefreshDrawingInformation(){var doc=AcadApplication.DocumentManager.MdiActiveDocument;if(doc is null){_file.Text="Nenhum desenho aberto";_path.Text="—";return;}_file.Text=Path.GetFileName(doc.Name);_path.Text=Path.GetDirectoryName(doc.Name)??"Arquivo ainda não salvo";var latest=LocalVersionService.GetLatestVersion(doc.Name);_revision.Text=latest?.RevisionLabel??"Rascunho local";_latest.Text=latest?.CreatedAt.ToString("dd/MM/yyyy HH:mm:ss")??"Nenhuma versão criada";}
 public void ShowVersionCreated(LocalVersionInfo v)=>Run(()=>{_revision.Text=v.RevisionLabel;_latest.Text=v.CreatedAt.ToString("dd/MM/yyyy HH:mm:ss");_status.Text=$"✓ Versão {v.RevisionLabel} criada localmente";});public void ShowVersionError(string message)=>Run(()=>MessageBox.Show(message,"SquadEngineering — erro de versionamento",MessageBoxButtons.OK,MessageBoxIcon.Error));
 private void OpenVersions(){var doc=AcadApplication.DocumentManager.MdiActiveDocument;if(doc is null)return;var dir=LocalVersionService.GetVersionDirectory(doc.Name);Directory.CreateDirectory(dir);Process.Start(new ProcessStartInfo(dir){UseShellExecute=true});}private void Run(Action action){if(IsDisposed)return;if(InvokeRequired)BeginInvoke(action);else action();}
 private static Label Value(string text="—")=>new(){Text=text,Font=new("Segoe UI",9,FontStyle.Bold),AutoSize=true,MaximumSize=new(280,0),Margin=new(0,2,0,14)};private static Button ActionButton(string text)=>new(){Text=text,Width=280,Height=38,BackColor=Color.FromArgb(31,41,55),ForeColor=Color.White,Margin=new(0,6,0,0)};private static void Field(Control p,string caption,Control value){p.Controls.Add(new Label{Text=caption,Font=new("Segoe UI",7,FontStyle.Bold),AutoSize=true});p.Controls.Add(value);}
}
