using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
namespace SquadEngineering.Plugin;
internal sealed record LocalVersionInfo(int Revision,string RevisionLabel,string SourcePath,string VersionPath,DateTime CreatedAt);
internal static partial class LocalVersionService
{
 public static LocalVersionInfo CreateVersion(string drawingPath){var source=Path.GetFullPath(drawingPath);var dir=GetVersionDirectory(source);var name=Sanitize(Path.GetFileNameWithoutExtension(source));Directory.CreateDirectory(dir);for(var attempt=0;attempt<100;attempt++){var revision=Directory.EnumerateFiles(dir,"*.dwg").Select(p=>Parse(Path.GetFileName(p))).DefaultIfEmpty().Max()+1;var created=DateTime.Now;var destination=Path.Combine(dir,$"{name}_R{revision:0000}_{created:yyyyMMdd_HHmmss}.dwg");try{using(var input=new FileStream(source,FileMode.Open,FileAccess.Read,FileShare.ReadWrite|FileShare.Delete))using(var output=new FileStream(destination,FileMode.CreateNew,FileAccess.Write,FileShare.None)){input.CopyTo(output);output.Flush(true);}var info=new LocalVersionInfo(revision,$"R{revision:0000}",source,destination,created);WriteMetadata(info);return info;}catch(IOException)when(File.Exists(destination)){}}throw new IOException("Não foi possível reservar um número de revisão.");}
 public static LocalVersionInfo? GetLatestVersion(string drawingPath){if(string.IsNullOrWhiteSpace(drawingPath))return null;var source=Path.GetFullPath(drawingPath);var dir=GetVersionDirectory(source);if(!Directory.Exists(dir))return null;var latest=Directory.EnumerateFiles(dir,"*.dwg").Select(p=>(Path:p,Revision:Parse(Path.GetFileName(p)))).Where(x=>x.Revision>0).OrderByDescending(x=>x.Revision).FirstOrDefault();return latest.Revision==0?null:new(latest.Revision,$"R{latest.Revision:0000}",source,latest.Path,File.GetLastWriteTime(latest.Path));}
 public static string GetVersionDirectory(string drawingPath)=>Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"SquadSystem","SquadEngineering","Versoes",$"{Sanitize(Path.GetFileNameWithoutExtension(drawingPath))}_{Key(Path.GetFullPath(drawingPath))}");
 private static void WriteMetadata(LocalVersionInfo v)=>File.WriteAllText(Path.ChangeExtension(v.VersionPath,".json"),JsonSerializer.Serialize(new{revision=v.Revision,revisionLabel=v.RevisionLabel,sourcePath=v.SourcePath,versionPath=v.VersionPath,createdAt=v.CreatedAt,windowsUser=Environment.UserName,computer=Environment.MachineName,fileSize=new FileInfo(v.VersionPath).Length},new JsonSerializerOptions{WriteIndented=true}),Encoding.UTF8);
 private static int Parse(string name){var m=RevisionPattern().Match(name);return m.Success&&int.TryParse(m.Groups[1].Value,out var value)?value:0;} private static string Key(string path)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(path.Trim().ToUpperInvariant())))[..8]; private static string Sanitize(string value){var invalid=Path.GetInvalidFileNameChars();var result=new string(value.Select(c=>invalid.Contains(c)?'_':c).ToArray());return string.IsNullOrWhiteSpace(result)?"Desenho":result;} [GeneratedRegex(@"_R(\d{4})_",RegexOptions.IgnoreCase)] private static partial Regex RevisionPattern();
}
