-- SquadMeasure Fase 1: domínio, permissões, helpers e RLS (single-tenant).
CREATE TABLE measure_visitas (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), obra_id uuid NOT NULL REFERENCES obras(id), medidor_responsavel_id uuid NOT NULL REFERENCES usuarios(id),
 status text NOT NULL DEFAULT 'agendada' CHECK (status IN ('agendada','disponivel_offline','em_deslocamento','em_andamento','pausada','aguardando_sincronizacao','aguardando_revisao','correcao_solicitada','concluida','cancelada')),
 prioridade text NOT NULL DEFAULT 'normal' CHECK (prioridade IN ('baixa','normal','alta','urgente')), agendada_para timestamptz, iniciada_em timestamptz, finalizada_em timestamptz,
 observacoes_gerais text, progresso integer NOT NULL DEFAULT 0 CHECK (progresso BETWEEN 0 AND 100), justificativa_finalizacao text, contexto_obra_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
 versao integer NOT NULL DEFAULT 1 CHECK (versao >= 1), criado_por uuid NOT NULL REFERENCES usuarios(id), atualizado_por uuid REFERENCES usuarios(id), criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NOT NULL DEFAULT now(), excluido_em timestamptz,
 CHECK (finalizada_em IS NULL OR iniciada_em IS NOT NULL), CHECK (finalizada_em IS NULL OR finalizada_em >= iniciada_em)
);
CREATE TABLE measure_visita_membros (visita_id uuid NOT NULL REFERENCES measure_visitas(id) ON DELETE CASCADE, usuario_id uuid NOT NULL REFERENCES usuarios(id), papel_na_visita text NOT NULL CHECK (papel_na_visita IN ('responsavel','medidor','assistente','revisor','visualizador')), criado_em timestamptz NOT NULL DEFAULT now(), criado_por uuid NOT NULL REFERENCES usuarios(id), PRIMARY KEY (visita_id, usuario_id));
CREATE TABLE measure_ambientes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), visita_id uuid NOT NULL REFERENCES measure_visitas(id), nome text NOT NULL CHECK (btrim(nome) <> ''), codigo text, pavimento text, descricao text, sequencia integer NOT NULL DEFAULT 0 CHECK (sequencia >= 0), status text NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente','em_andamento','concluido')), observacoes text, arquivado_em timestamptz, versao integer NOT NULL DEFAULT 1 CHECK (versao >= 1), criado_por uuid NOT NULL REFERENCES usuarios(id), atualizado_por uuid REFERENCES usuarios(id), criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NOT NULL DEFAULT now(), excluido_em timestamptz);
CREATE TABLE measure_elementos (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ambiente_id uuid NOT NULL REFERENCES measure_ambientes(id), nome text NOT NULL CHECK (btrim(nome) <> ''), codigo text, tipo text NOT NULL CHECK (btrim(tipo) <> ''), quantidade integer NOT NULL DEFAULT 1 CHECK (quantidade > 0), descricao text, sequencia integer NOT NULL DEFAULT 0 CHECK (sequencia >= 0), status text NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente','em_andamento','concluido')), requer_atencao boolean NOT NULL DEFAULT false, responsavel_registro_id uuid REFERENCES usuarios(id), arquivado_em timestamptz, versao integer NOT NULL DEFAULT 1 CHECK (versao >= 1), criado_por uuid NOT NULL REFERENCES usuarios(id), atualizado_por uuid REFERENCES usuarios(id), criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NOT NULL DEFAULT now(), excluido_em timestamptz);
CREATE TABLE measure_medidas (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), elemento_id uuid NOT NULL REFERENCES measure_elementos(id), grupo text, tipo text NOT NULL CHECK (tipo IN ('largura','altura','profundidade','diagonal_1','diagonal_2','espessura','folga','nivel','prumo','distancia','raio','angulo','quantidade','personalizada')), nome text NOT NULL CHECK (btrim(nome) <> ''), valor numeric NOT NULL, unidade text NOT NULL CHECK (unidade IN ('mm','cm','m','graus','unidade')), tolerancia numeric CHECK (tolerancia IS NULL OR tolerancia >= 0), posicao text, observacao text, origem text NOT NULL CHECK (origem IN ('manual','importada')), estado text NOT NULL CHECK (estado IN ('provisoria','confirmada','revisar','invalidada')), responsavel_id uuid NOT NULL REFERENCES usuarios(id), medida_em timestamptz NOT NULL DEFAULT now(), versao integer NOT NULL DEFAULT 1 CHECK (versao >= 1), criado_por uuid NOT NULL REFERENCES usuarios(id), atualizado_por uuid REFERENCES usuarios(id), criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NOT NULL DEFAULT now(), excluido_em timestamptz);
CREATE TABLE measure_observacoes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), visita_id uuid NOT NULL REFERENCES measure_visitas(id), ambiente_id uuid REFERENCES measure_ambientes(id), elemento_id uuid REFERENCES measure_elementos(id), medida_id uuid REFERENCES measure_medidas(id), categoria text NOT NULL CHECK (categoria IN ('informacao','atencao','impedimento','decisao_cliente','pendencia','risco','revisao_necessaria')), texto text NOT NULL CHECK (btrim(texto) <> ''), importante boolean NOT NULL DEFAULT false, resolvida_em timestamptz, responsavel_id uuid NOT NULL REFERENCES usuarios(id), criado_por uuid NOT NULL REFERENCES usuarios(id), atualizado_por uuid REFERENCES usuarios(id), criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NOT NULL DEFAULT now(), excluido_em timestamptz, CHECK (num_nonnulls(ambiente_id, elemento_id, medida_id) <= 1));
CREATE TABLE measure_historico (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), visita_id uuid NOT NULL REFERENCES measure_visitas(id), usuario_id uuid NOT NULL REFERENCES usuarios(id), acao text NOT NULL, entidade_tipo text NOT NULL, entidade_id uuid, dados_antes jsonb, dados_depois jsonb, criado_em timestamptz NOT NULL DEFAULT now());

CREATE INDEX idx_measure_visitas_obra ON measure_visitas(obra_id); CREATE INDEX idx_measure_visitas_medidor ON measure_visitas(medidor_responsavel_id); CREATE INDEX idx_measure_visitas_status ON measure_visitas(status); CREATE INDEX idx_measure_visitas_agendada ON measure_visitas(agendada_para); CREATE INDEX idx_measure_visitas_ativos ON measure_visitas(criado_em DESC) WHERE excluido_em IS NULL;
CREATE INDEX idx_measure_membros_usuario ON measure_visita_membros(usuario_id); CREATE INDEX idx_measure_ambientes_visita_seq ON measure_ambientes(visita_id, sequencia) WHERE excluido_em IS NULL; CREATE INDEX idx_measure_elementos_ambiente_seq ON measure_elementos(ambiente_id, sequencia) WHERE excluido_em IS NULL; CREATE INDEX idx_measure_medidas_elemento ON measure_medidas(elemento_id) WHERE excluido_em IS NULL; CREATE INDEX idx_measure_medidas_tipo ON measure_medidas(tipo); CREATE INDEX idx_measure_medidas_estado ON measure_medidas(estado); CREATE INDEX idx_measure_obs_visita ON measure_observacoes(visita_id) WHERE excluido_em IS NULL; CREATE INDEX idx_measure_obs_ambiente ON measure_observacoes(ambiente_id) WHERE ambiente_id IS NOT NULL; CREATE INDEX idx_measure_obs_elemento ON measure_observacoes(elemento_id) WHERE elemento_id IS NOT NULL; CREATE INDEX idx_measure_obs_medida ON measure_observacoes(medida_id) WHERE medida_id IS NOT NULL; CREATE INDEX idx_measure_historico_visita_data ON measure_historico(visita_id, criado_em DESC);

INSERT INTO permissoes (chave, nome, modulo) VALUES
 ('squadmeasure.visualizar','Visualizar SquadMeasure','SQUADMEASURE'),('squadmeasure.criar_visita','Criar visita','SQUADMEASURE'),('squadmeasure.editar_visita','Editar visita','SQUADMEASURE'),('squadmeasure.cancelar_visita','Cancelar visita','SQUADMEASURE'),('squadmeasure.executar_medicao','Executar medição','SQUADMEASURE'),('squadmeasure.finalizar_medicao','Finalizar medição','SQUADMEASURE'),('squadmeasure.reabrir_medicao','Reabrir medição','SQUADMEASURE'),('squadmeasure.revisar_medicao','Revisar medição','SQUADMEASURE'),('squadmeasure.registrar_medidas','Registrar medidas','SQUADMEASURE'),('squadmeasure.gerenciar_ambientes','Gerenciar ambientes','SQUADMEASURE'),('squadmeasure.gerenciar_elementos','Gerenciar elementos','SQUADMEASURE'),('squadmeasure.gerenciar_observacoes','Gerenciar observações','SQUADMEASURE'),('squadmeasure.visualizar_historico','Visualizar histórico','SQUADMEASURE') ON CONFLICT (chave) DO NOTHING;

CREATE OR REPLACE FUNCTION measure_fn_pode_ver_visita(p_visita_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS (SELECT 1 FROM measure_visitas v WHERE v.id=p_visita_id AND v.excluido_em IS NULL AND fn_auth_tem_permissao('squadmeasure.visualizar') AND (fn_auth_is_admin() OR v.medidor_responsavel_id=fn_auth_user_db_id() OR EXISTS (SELECT 1 FROM measure_visita_membros m WHERE m.visita_id=v.id AND m.usuario_id=fn_auth_user_db_id()))) $$;
CREATE OR REPLACE FUNCTION measure_fn_pode_editar_visita(p_visita_id uuid, p_permissao text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS (SELECT 1 FROM measure_visitas v WHERE v.id=p_visita_id AND v.excluido_em IS NULL AND fn_auth_tem_permissao(p_permissao) AND (fn_auth_is_admin() OR v.medidor_responsavel_id=fn_auth_user_db_id() OR EXISTS (SELECT 1 FROM measure_visita_membros m WHERE m.visita_id=v.id AND m.usuario_id=fn_auth_user_db_id() AND m.papel_na_visita IN ('responsavel','medidor','revisor')))) $$;
CREATE OR REPLACE FUNCTION measure_fn_visita_do_ambiente(p_ambiente_id uuid) RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT visita_id FROM measure_ambientes WHERE id=p_ambiente_id LIMIT 1 $$;
CREATE OR REPLACE FUNCTION measure_fn_visita_do_elemento(p_elemento_id uuid) RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT a.visita_id FROM measure_elementos e JOIN measure_ambientes a ON a.id=e.ambiente_id WHERE e.id=p_elemento_id LIMIT 1 $$;
REVOKE ALL ON FUNCTION measure_fn_pode_ver_visita(uuid), measure_fn_pode_editar_visita(uuid,text), measure_fn_visita_do_ambiente(uuid), measure_fn_visita_do_elemento(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION measure_fn_pode_ver_visita(uuid), measure_fn_pode_editar_visita(uuid,text), measure_fn_visita_do_ambiente(uuid), measure_fn_visita_do_elemento(uuid) TO authenticated;

ALTER TABLE measure_visitas ENABLE ROW LEVEL SECURITY; ALTER TABLE measure_visita_membros ENABLE ROW LEVEL SECURITY; ALTER TABLE measure_ambientes ENABLE ROW LEVEL SECURITY; ALTER TABLE measure_elementos ENABLE ROW LEVEL SECURITY; ALTER TABLE measure_medidas ENABLE ROW LEVEL SECURITY; ALTER TABLE measure_observacoes ENABLE ROW LEVEL SECURITY; ALTER TABLE measure_historico ENABLE ROW LEVEL SECURITY;
CREATE POLICY measure_visitas_select ON measure_visitas FOR SELECT TO authenticated USING (measure_fn_pode_ver_visita(id));
CREATE POLICY measure_visitas_insert ON measure_visitas FOR INSERT TO authenticated WITH CHECK (fn_auth_tem_permissao('squadmeasure.criar_visita') AND criado_por=fn_auth_user_db_id());
CREATE POLICY measure_visitas_update ON measure_visitas FOR UPDATE TO authenticated USING (measure_fn_pode_editar_visita(id,'squadmeasure.editar_visita')) WITH CHECK (measure_fn_pode_editar_visita(id,'squadmeasure.editar_visita'));
CREATE POLICY measure_membros_select ON measure_visita_membros FOR SELECT TO authenticated USING (measure_fn_pode_ver_visita(visita_id)); CREATE POLICY measure_membros_write ON measure_visita_membros FOR ALL TO authenticated USING (measure_fn_pode_editar_visita(visita_id,'squadmeasure.editar_visita')) WITH CHECK (measure_fn_pode_editar_visita(visita_id,'squadmeasure.editar_visita'));
CREATE POLICY measure_ambientes_select ON measure_ambientes FOR SELECT TO authenticated USING (measure_fn_pode_ver_visita(visita_id)); CREATE POLICY measure_ambientes_write ON measure_ambientes FOR ALL TO authenticated USING (measure_fn_pode_editar_visita(visita_id,'squadmeasure.gerenciar_ambientes')) WITH CHECK (measure_fn_pode_editar_visita(visita_id,'squadmeasure.gerenciar_ambientes'));
CREATE POLICY measure_elementos_select ON measure_elementos FOR SELECT TO authenticated USING (measure_fn_pode_ver_visita(measure_fn_visita_do_ambiente(ambiente_id))); CREATE POLICY measure_elementos_write ON measure_elementos FOR ALL TO authenticated USING (measure_fn_pode_editar_visita(measure_fn_visita_do_ambiente(ambiente_id),'squadmeasure.gerenciar_elementos')) WITH CHECK (measure_fn_pode_editar_visita(measure_fn_visita_do_ambiente(ambiente_id),'squadmeasure.gerenciar_elementos'));
CREATE POLICY measure_medidas_select ON measure_medidas FOR SELECT TO authenticated USING (measure_fn_pode_ver_visita(measure_fn_visita_do_elemento(elemento_id))); CREATE POLICY measure_medidas_write ON measure_medidas FOR ALL TO authenticated USING (measure_fn_pode_editar_visita(measure_fn_visita_do_elemento(elemento_id),'squadmeasure.registrar_medidas')) WITH CHECK (measure_fn_pode_editar_visita(measure_fn_visita_do_elemento(elemento_id),'squadmeasure.registrar_medidas'));
CREATE POLICY measure_obs_select ON measure_observacoes FOR SELECT TO authenticated USING (measure_fn_pode_ver_visita(visita_id)); CREATE POLICY measure_obs_write ON measure_observacoes FOR ALL TO authenticated USING (measure_fn_pode_editar_visita(visita_id,'squadmeasure.gerenciar_observacoes')) WITH CHECK (measure_fn_pode_editar_visita(visita_id,'squadmeasure.gerenciar_observacoes'));
CREATE POLICY measure_hist_select ON measure_historico FOR SELECT TO authenticated USING (measure_fn_pode_ver_visita(visita_id) AND fn_auth_tem_permissao('squadmeasure.visualizar_historico'));
CREATE POLICY measure_hist_insert ON measure_historico FOR INSERT TO authenticated WITH CHECK (measure_fn_pode_ver_visita(visita_id) AND usuario_id=fn_auth_user_db_id());
